# This is a basic workflow to help you get started with Actions

name: CI-Carvices

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "develop" ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend/Carvices.API 
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore ${{env.working-directory}}\backend\Carvices.API
      - name: Build
        run: dotnet build --no-restore ${{env.working-directory}}\backend\Carvices.API
      - name: Test
        run: dotnet test --no-build --verbosity normal ${{env.working-directory}}\backend\Carvices.API
